name: danp04
title: Portfolio
description: An example of self-developed content hosted on Github pages, using the Just the Docs Jekyll theme
remote_theme: danp04/just-the-docs

color_scheme: new_color


aux_links:
  "Source repository on GitHub":
    - "//github.com/danp04/Portfolio"

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "The documentation is part of the reference materials for the Technical Communication course at Vistula University (Warsaw). 